name: Docker build and publish to GHCR

on:
  push:
    branches: 
      - main
  release:
    types: [published] # will use tag name regardless of naming

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to the Container registry
        run:  docker login --username pigeonport --password ${{secrets.GHCR_MARV_PERSONAL}} ghcr.io

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pigeonport/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest

      - name: display Infos
        run: | 
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
